nombre = input ( " Cual es tu nombre?")
edad = input ("cual es tu edad?")
cuidad = input ("Cual es tu ciudad natal?")
casado = input ("Eres casado?")
numero_a = input ("introduce un numero entero")
numero_a = int(numero_a)
numero_b = input ("introduce un segundo numero entero")
numero_b = int(numero_b)
print(f"Mi nombre es :{nombre}, mi edad es {edad} años,soy de la cuidad {cuidad} y mi resultado es {numero_b / numero_a}" )